export const urls = [
  'https://www.seriousscrum.com/',
  'https://thomasjfrank.com/notion-databases-the-ultimate-beginners-guide',
  'https://www.mountaingoatsoftware.com/blog',
  'https://scaledagileframework.com/',
  'https://www.scrum.org/resources',
  'https://www.scruminc.com/scrumlab-open',
  'https://ronjeffries.com/categories.html',
  'https://gojko.net/posts.html',
  'https://www.funretrospectives.com/',
  'https://age-of-product.com/',
  'https://estherderby.com/blog/',
  'https://jpattonassociates.com/category/articles/',
  'https://gamestorming.com/blog/',
  'https://availagility.co.uk/',
  'https://tastycupcakes.org/',

